---
- id: extract-vba-code
  name: Extract VBA code from Excel files
  description: Extracts VBA code from Excel files and saves it in a specified directory.
  entry: pre-commit-vba
  args: [extract]
  language: python
  files: \.xlsm$|\.xlsb$|\.xls$|\.xltm$|\.xlam$
  exclude: ^(?!.*\.(xlsm|xlsb|xls|xltm|xlam)$).*$
  pass_filenames: false
- id: check-excel-book-version
  name: Check Excel book version
  description: Checks the version of Excel books to ensure compatibility with the current branch name.
  entry: pre-commit-vba
  args: [check]
  language: python
  always_run: true
  pass_filenames: false
