---
- id: extract-vba-code
  name: Extract VBA code from Office files
  description: Extracts VBA code from Office files and saves it in a specified directory.
  entry: pre-commit-vba
  args: [extract]
  language: python
  files: (?i)\.(xlsm|xltm|xlam|docm|dotm|pptm|potm)$
  pass_filenames: false
- id: check-office-file-integrity
  name: Check Office file integrity
  description: Checks Office file versions against the current branch name and detects Rubberduck Addin references.
  entry: pre-commit-vba
  args: [check]
  language: python
  always_run: true
  pass_filenames: false
- id: check-excel-book-version
  name: "[DEPRECATED] Compatibility alias for check-office-file-integrity"
  description: Deprecated compatibility alias for check-office-file-integrity. Checks Office file versions against the current branch name and detects Rubberduck Addin references.
  entry: pre-commit-vba
  args: [check]
  language: python
  always_run: true
  pass_filenames: false
