Attribute VB_Name = "Constants"
'@Folder "src"
Option Explicit

Public Enum AppError
    [_Base_Error] = vbObjectError + 1024
    BRANCH_VERSION_COMMAND_FAILED
    BRANCH_VERSION_CURRENT_DIRECTORY_SET_FAILED
    BRANCH_VERSION_WORKBOOK_PATH_NOT_SET
    GIT_NOT_INSTALLED_OR_CONFIGURED
    HAS_CREATED
    INVALID_SEMVER
    INVALID_VALUE
    MISSING_PROPERTY
    NOT_CREATED
    VERSION_ROLLBACK_NOT_ALLOWED
End Enum
